import AboutPage from '@/components/about/AboutPage'
import Education from '@/components/Education';
import Experience from '@/components/Experience';
import SkillsSection from '@/components/Skills';
import React from 'react'

export const metadata = {
  title: "About | Abdul Mazid Akash",
  description: "Generated by create next app",
};

export default function About() {
  return (
	<div className='pt-16 w-10/12 mx-auto'>
		<AboutPage/>
    <SkillsSection/>
    <Experience/>
    <Education/>
	</div>
  )
}
