import AboutPage from '@/components/about/AboutPage'
import React from 'react'
export const metadata = {
  title: "About | Abdul Mazid Akash",
  description: "Generated by create next app",
};

export default function About() {
  return (
	<div>
		<AboutPage/>
	</div>
  )
}
