import React from 'react'
import ProjectsPage from './components/ProjectPage';

export const metadata = {
  title: "Projects | Abdul Mazid Akash",
  description: "Generated by create next app",
};

export default function Projects() {
  return (
	<div>
		<ProjectsPage/>
	</div>
  )
}
