import React from 'react'
import ArticlesPage from './components/ArticlePage';
import TransitionEffect from '@/components/TransitionEffect';
import InterQandA from './components/InterQandA';
import HtmlQandA from './components/HtmlQandA';
import CssQandA from './components/CssQandA';
import JsQandA from './components/JsQandA';

export const metadata = {
  title: "Articles | Abdul Mazid Akash",
  description: "Generated by create next app",
};

export default function Article() {
  return (
	<div className='text-dark'>
    <TransitionEffect/>
		<ArticlesPage/>
    <InterQandA/>
    <HtmlQandA/>
    <CssQandA/>
    <JsQandA/>
	</div>
  )
}
