import React from 'react'
import ArticlesPage from './components/ArticlePage';

export const metadata = {
  title: "Articles | Abdul Mazid Akash",
  description: "Generated by create next app",
};

export default function Article() {
  return (
	<div>
		<ArticlesPage/>
	</div>
  )
}
