import React from 'react'
import ArticlesPage from './components/ArticlePage';
import TransitionEffect from '@/components/TransitionEffect';

export const metadata = {
  title: "Articles | Abdul Mazid Akash",
  description: "Generated by create next app",
};

export default function Article() {
  return (
	<div>
    <TransitionEffect/>
		<ArticlesPage/>
	</div>
  )
}
